routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\todo_controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


Route::resource('todo',todo_controller::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class todo extends Model
{
    use HasFactory;
    protected $fillable = [
        'to','do'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/todo_controller.php
<?php

namespace App\Http\Controllers;

use App\Models\todo;
use Illuminate\Http\Request;

class todo_controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todos = todo::all();
        return view('show',compact('todos'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->all());

        todo::create([
            'to' => $request->to,
            'do' => $request->do
        ]);

        return redirect()->route('todo.index')->with('msg' , 'با موفقیت ثبت شد');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $todo = todo::where('id',$id)->first();

        return view('update',compact('todo'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        todO::where('id',$id)->update([
            'to' => $request->to,
            'do' => $request->do,
        ]);

        return redirect()->route('todo.index')->with('msgup' , 'با موفقیت اپدیت شد');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(todo $todo)
    {

        $todo->Delete();
        return redirect()->route('todo.index')->with('msgdelet' , 'با موفقیت حذف شد');

    }
}

resources/views/create.blade.php
@extends('layout.master')

@section('contant')

    <form action="{{route('todo.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="exampleInputEmail1">TODO</label>
            <input validated name="to" type="text" class="form-control" id="exampleInputEmail1"  placeholder="TOdo">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Description</label>
            <input name="do" type="text" class="form-control" id="exampleInputPassword1" placeholder="Description">
        </div>

        <button type="submit" class="btn btn-success">Add</button>
    </form>

@endsection

resources/views/layout/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>ToDoList</title>
</head>
<body>

<div class="container">
<br>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand btn btn-warning " type="button" href="{{ route('todo.create')}}">Add</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{{ route('todo.index') }}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Login</a>
            <a class="nav-item nav-link" href="#">Logout</a>
        </div>
    </div>
</nav>

    <br>
    <br>
    <br>
    <br>
    @yield('contant')
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

resources/views/show.blade.php
@extends('layout.master')

@section('contant')
        @if($masseg = Session::get('msg'))
            <div class="alert alert-success">
                {{ $masseg }}
            </div>

        @endif


    @if($masseg = Session::get('msgdelet'))
        <div class="alert alert-success">
            {{ $masseg }}
        </div>

    @endif

        @if($masseg = Session::get('msgup'))
            <div class="alert alert-success">
                {{ $masseg }}
            </div>

        @endif

    @foreach($todos as $todo)

    <div class="card">
        <div class="card-header">
            ID : {{$todo['id']}}
        </div>
        <div class="card-body">
            <h3 class="card-title">{{$todo['to']}}</h3>
            <p> {{$todo['created_at']}}</p>
            <h5 class="card-text">{{$todo['do']}}</h5>
            <a href="{{ route('todo.edit' , $todo['id']) }}" class="btn btn-secondary">Edit</a>
            <form action="{{ route('todo.destroy' , ['todo' => $todo->id]) }}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Delet</button>
            </form>
        </div>
    </div>
        <br><br>
    @endforeach

@endsection

resources/views/update.blade.php
@extends('layout.master')

@section('contant')

    <form action="{{ route('todo.update' , ['todo' => $todo->id]) }}" method="post" >
        @csrf
        @method('put')
        <div class="form-group">
            <label for="exampleInputEmail1">Edit TODO</label>
            <input name="to" value="{{ $todo['to'] }}" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Edit TODO">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Edit Description</label>
            <input name="do" value="{{ $todo['do'] }}" type="text" class="form-control" id="exampleInputPassword1" placeholder="Edit Description">
        </div>

        <button type="submit" class="btn btn-secondary">Edit</button>
    </form>

@endsection